image: docker:latest

services:
  - docker:dind

stages:
  - build
  - container-build
  - test
  - deploy-dev
  - deploy-frontend-dev
  - deploy-test
  - deploy-prod

include:
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

variables:
  SECURE_LOG_LEVEL: info
  DS_JAVA_VERSION: 11
  DOCKER_DRIVER: overlay
  CONTAINER_IMAGE: smartcommunitylab/gamification-engine:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  CONTAINER_IMAGE_LATEST: smartcommunitylab/gamification-engine:$CI_COMMIT_REF_NAME-latest
  CONTAINER_CACHE_IMAGE: smartcommunitylab/gamification-engine:cache
  CONTAINER_FRONTEND_IMAGE: smartcommunitylab/gamification-engine-frontend:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  CONTAINER_FRONTEND_IMAGE_LATEST: smartcommunitylab/gamification-engine-frontend:$CI_COMMIT_REF_NAME-latest
  CONTAINER_FRONTEND_CACHE_IMAGE: smartcommunitylab/gamification-engine-frontend:cache

update-backend-cache-image:
  stage: build
  variables:
    BUILDKIT_PROGRESS: plain
    DOCKER_BUILDKIT: 1 
  script:
    - docker login -u $DHUB_USER -p $DHUB_PASS
    - docker build -f Dockerfile-cache -t CONTAINER_CACHE_IMAGE .
    - docker push $CONTAINER_CACHE_IMAGE
  rules:
    - changes:
      - game-engine.core/pom.xml
      - game-engine.web/pom.xml

update-frontend-cache-image:
  stage: build
  variables:
    BUILDKIT_PROGRESS: plain
    DOCKER_BUILDKIT: 1 
  script:
    - docker login -u $DHUB_USER -p $DHUB_PASS
    - cd gamification-frontend
    - docker build -f Dockerfile-cache -t CONTAINER_FRONTEND_CACHE_IMAGE .
    - docker push $CONTAINER_FRONTEND_CACHE_IMAGE
  rules:
    - changes:
      - gamification-frontend/package.json

maven-build:
  image: maven:3-openjdk-11
  stage: build
  script:
    - cd ${CI_PROJECT_DIR}/game-engine.core
    - mvn -DskipTests=true clean install -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2
    - cd ${CI_PROJECT_DIR}/game-engine.web
    - mvn clean install -DskipTests -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2
    - cd ${CI_PROJECT_DIR}/game-engine.tools/log2timescaledb
    - mvn clean install -DskipTests -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/.m2/
      - game-engine.core/
      - game-engine.web/
      - game-engine.tools/log2timescaledb
    expire_in: 1 week
  only:
    - master

spotbugs-sast:
  dependencies:
    - maven-build
  variables:
    MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/
    SECURE_LOG_LEVEL: "debug"
    SAST_JAVA_VERSION: 11
    COMPILE: "false"
    SAST_EXCLUDED_PATHS: "geme-engine.games, game-engine.test, game-engine.tools, gamification-java-client"
    SAST_BANDIT_EXCLUDED_PATHS: '*/geme-engine.games/*, */game-engine.test/*, */game-engine.tools/*, */gamification-java-client/*'
  artifacts:
    reports:
      sast: gl-sast-report.json
    expire_in: 1 week
  rules:
     - if: '$CI_COMMIT_REF_NAME == "master"'

semgrep-sast:
  rules:
     - if: '$CI_COMMIT_REF_NAME == "master"'

nodejs-scan-sast:
  rules:
     - if: '$CI_COMMIT_REF_NAME == "master"'

gemnasium-maven-dependency_scanning:
  rules:
     - if: '$CI_COMMIT_REF_NAME == "master"'

backend-container-build:
  stage: container-build
  variables:
    BUILDKIT_PROGRESS: plain
    DOCKER_BUILDKIT: 1 
  script:
    - docker login -u $DHUB_USER -p $DHUB_PASS
    - docker build -f Dockerfile -t $CONTAINER_IMAGE -t $CONTAINER_IMAGE_LATEST .
    - docker push $CONTAINER_IMAGE
    - docker push $CONTAINER_IMAGE_LATEST
  only:
    - playAndGo-dev-v2
    - playAndGo-prod-v2
    - master
  artifacts:
    expire_in: 1 week

frontend-container-build:
  stage: container-build
  variables:
    BUILDKIT_PROGRESS: plain
    DOCKER_BUILDKIT: 1 
  script:
    - docker login -u $DHUB_USER -p $DHUB_PASS
    - cd gamification-frontend
    - docker build -f Dockerfile --build-arg REACT_APP_API_ENDPOINT=https://gedev.playngo.it/gamification -t $CONTAINER_FRONTEND_IMAGE -t $CONTAINER_FRONTEND_IMAGE_LATEST .
    - docker push $CONTAINER_FRONTEND_IMAGE
    - docker push $CONTAINER_FRONTEND_IMAGE_LATEST
  only:
    - playAndGo-dev-v2
  artifacts:
    expire_in: 1 week

container_scanning:
  stage: test
  dependencies:
  - backend-container-build
  variables:
    DOCKER_IMAGE: smartcommunitylab/gamification-engine:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    DOCKERFILE_PATH: "Dockerfile"
    GIT_STRATEGY: fetch
    DOCKER_USER: ""
    DOCKER_PASSWORD: ""
  artifacts:
    expire_in: 1 week
  rules:
     - if: '$CI_COMMIT_REF_NAME == "master"'
    
deploy-dev:
  stage: deploy-dev
  image: 
    name: bitnami/kubectl:latest
    entrypoint: ['']
  environment:
    name: platform-new
  script:
    - echo "deploy backend"
    - kubectl -n playngo-dev set image deployments/gamification-engine gamification-engine=$CONTAINER_IMAGE --record=true
    - kubectl -n playngo-dev rollout status deployment gamification-engine
  only:
    - playAndGo-dev-v2

deploy-frontend-dev:
  stage: deploy-frontend-dev
  image: 
    name: bitnami/kubectl:latest
    entrypoint: ['']
  environment:
    name: platform-new
  script:
    - echo "deploy frontend"
    - kubectl -n playngo-dev set image deployments/gamification-frontend gamification-frontend=$CONTAINER_FRONTEND_IMAGE --record=true
    - kubectl -n playngo-dev rollout status deployment gamification-frontend
  only:
    - playAndGo-dev-v2

deploy-test:
  stage: deploy-test
  image: 
    name: bitnami/kubectl:latest
    entrypoint: ['']
  environment:
    name: platform-new
  script:
    - echo "deploy backend"
    - kubectl -n gamification-test set image deployments/gamification-engine gamification-engine=$CONTAINER_IMAGE --record=true
    - kubectl -n gamification-test rollout status deployment gamification-engine
  only:
    - playAndGo-dev-v2

deploy-prod:
  stage: deploy-prod
  image: 
    name: bitnami/kubectl:latest
    entrypoint: ['']
  environment:
    name: platform-new
  script:
    - echo "deploy backend"
    - kubectl -n playngo-prod set image deployments/gamification-engine gamification-engine=$CONTAINER_IMAGE --record=true
    - kubectl -n playngo-prod rollout status deployment gamification-engine
  only:
    - playAndGo-prod-v2
